export const ActionTypes = {
  FETCH_SLIDERS: "FETCH_SLIDERS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORY_PRODUCTS: "FETCH_CATEGORY_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_FAVORITES: "FETCH_FAVORITES",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
};
