export const ActionTypes = {
  FETCH_SLIDERS: "FETCH_SLIDERS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORY_PRODUCTS: "FETCH_CATEGORY_PRODUCTS",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",
  FETCH_FAVORITES: "FETCH_FAVORITES",
};
