export const ActionTypes = {
  SET_SLIDERS: "SET_SLIDERS",
  FETCH_SLIDERS: "FETCH_SLIDERS",
  SET_CATEGORIES: "SET_CATEGORIES",
  GET_CATEGORY_PRODUCTS: "GET_CATEGORY_PRODUCTS",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",
  GET_FAVORITES: "GET_FAVORITES",
};
